### PR TITLE
Allow to build shared library on Linux on Mac OS X

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we adapt the Makefile so it builds the shared library for Linux
and Mac OS X. Cross compilation is not supported.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
@peter-lawrey This is a follow-up of the open issues in #45 and includes also the new binaries for Mac OS X.

**Comment by danielmitterdorfer** [comment]
@peter-lawrey Any update on this PR? Do you need anything else?

**Comment by peter-lawrey** [comment]
Thank you for the bump.  I missed this merge. Done now.

**Comment by danielmitterdorfer** [comment]
No worries. Thanks for merging. Do you think you'll release a new version of the library any time soon?

**Comment by peter-lawrey** [comment]
We were not planning any releases this week. We can do a release next week.

**Comment by danielmitterdorfer** [comment]
Oh, I did not expect a release this week at all. Next week is great. Thank you!

**Comment by peter-lawrey** [comment]
This builds on our Linux build server so it shouldn't be a problem.

**Pull request merged**
