### PR TITLE
Use NativeAffinity on Mac OS X

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we'll use `NativeAffinity` again on Mac OS X by fixing the path to the native library. In addition, we include the native library also as a `.dylib` in order to support JDK 8.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
Note that this PR still does not work because there is still a problem with the native library. When acquiring an `AffinityLock` on Mac OS X, we get:

```
java.lang.UnsatisfiedLinkError: com.higherfrequencytrading.affinity.impl.NativeAffinity.getAffinity0()J
	at com.higherfrequencytrading.affinity.impl.NativeAffinity.getAffinity0(Native Method)
	at com.higherfrequencytrading.affinity.impl.NativeAffinity.getAffinity(NativeAffinity.java:49)
	at com.higherfrequencytrading.affinity.AffinitySupport.getAffinity(AffinitySupport.java:55)
	at com.higherfrequencytrading.affinity.AffinityLock.<clinit>(AffinityLock.java:44)
```

The reason is that the dynamic library that is included seems to export old symbols before a package refactoring. If I run `nm -gU libaffinity.dylib`, I get:

```
0000000000000afc T _Java_vanilla_java_affinity_impl_NativeAffinity_getAffinity0
0000000000000b75 T _Java_vanilla_java_affinity_impl_NativeAffinity_setAffinity0
0000000000000cb3 T _Java_vanilla_java_busywaiting_impl_JNIBusyWaiting_pause0
0000000000000cc9 T _Java_vanilla_java_busywaiting_impl_JNIBusyWaiting_whileEqual0
0000000000000d26 T _Java_vanilla_java_busywaiting_impl_JNIBusyWaiting_whileLessThan0
0000000000000c75 T _Java_vanilla_java_clock_impl_JNIClock_rdtsc0
```

I have looked at the Makefile in the project but I have no clue how the Mac OS X binary has been built.

**Comment by peter-lawrey** [comment]
Merged the changes. I don't have a Mac OSX so any assistance you can provide would be appreciated.

**Comment by danielmitterdorfer** [comment]
@peter-lawrey Sure, I can test but as I've written in the comment above, the dynamic library binary for Mac OS X is outdated and I have no clue how it should be built for Mac OS X (the Makefile seems to be Linux specific?).

**Comment by peter-lawrey** [comment]
I had hoped that

A) it had worked for the person who write it
B) Makefiles work much the same on Mac OSX.

If there is a better way for Mac I am open to ideas.

**Comment by danielmitterdorfer** [comment]
Sorry for not being clear: I know how to use make and Mac OS X has support for it but the build script as is cannot build a dynamic library for Mac OS X. So I wondered / asked how this binary has been build (it has not been built with this Makefile). I see that I come up with something that covers both platforms.

**Pull request merged**
